language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then npm run deploy:dev; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run deploy:prod; fi
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/* kj@server.bykev.in:/var/www/roll-cal-dev; fi
    on:
      branch: dev
before_install:
- openssl aes-256-cbc -K $encrypted_0b0c4b85a4ad_key -iv $encrypted_0b0c4b85a4ad_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- sudo apt-get update
- sudo apt-get install nasm
addons:
  ssh_known_hosts: server.bykev.in

