language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
after_success:
- 
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_0b0c4b85a4ad_key -iv $encrypted_0b0c4b85a4ad_iv
  -in deploy_rsa.enc -out ~\/.ssh/travis/deploy_rsa -d
