language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - dev
script:
- if [ "$TRAVIS_BRANCH" = "dev" ]; then npm run build:dev; fi
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/* kj@server.bykev.in:/var/www/roll-cal/api; sudo pm2 restart rollcal-api-dev --update-env;
    fi
  on:
    branch: dev
before_install:
- openssl aes-256-cbc -K $encrypted_a005e6de492a_key -iv $encrypted_a005e6de492a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts: server.bykev.in
