language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build kj@server.bykev.in:/var/www/roll-cal-dev
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_0b0c4b85a4ad_key -iv $encrypted_0b0c4b85a4ad_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
