branches:
  only:
  - dev
  - /^(release|hotfix)\/.*$/
  - master
matrix:
  include:
  - name: "web"
    language: node_js
    node_js:
    - stable
    cache:
      directories:
      - web/node_modules
    branches:
      only:
      - dev
    script:
    - cd web
    - npm install
    - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then npm run build:dev; fi
    - if [[ "$TRAVIS_BRANCH" =~ ^(release|hotfix)\/.*$ ]]; then npm run build:prod; fi
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; fi
    deploy:
    - provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/web/build/* kj767@dream.bykev.in:/home/kj767/roll-cal.com;
        rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/web/build/.htaccess kj767@dream.bykev.in:/home/kj767/roll-cal.com;
        fi
      on:
        branch: master
    before_install:
    - openssl aes-256-cbc -K $encrypted_024b6d64651d_key -iv $encrypted_024b6d64651d_iv
      -in travis_rsa.enc -out /tmp/travis_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/travis_rsa
    - ssh-add /tmp/travis_rsa
    addons:
      ssh_known_hosts: dream.bykev.in
  - name: "api"
    language: node_js
    node_js:
    - stable
    cache:
      directories:
      - api/node_modules
    branches:
      only:
      - dev
    script:
    - cd api
    - npm install
    - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then npm run build:dev; fi
    - if [[ "$TRAVIS_BRANCH" =~ ^(release|hotfix)\/.*$ ]]; then npm run build:stage; fi
    - if [[ "$TRAVIS_BRANCH" == "master" ]]; then npm run build:prod; fi
    deploy:
    - provider: script
      skip_cleanup: true
      script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/api/build/rollcal-api.js kj767@dream.bykev.in:/home/kj767/api.roll-cal.com/app.js;
        fi
      on:
        branch: master
    before_install:
    - openssl aes-256-cbc -K $encrypted_024b6d64651d_key -iv $encrypted_024b6d64651d_iv
      -in travis_rsa.enc -out /tmp/travis_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/travis_rsa
    - ssh-add /tmp/travis_rsa
    addons:
      ssh_known_hosts: dream.bykev.in
